
service: default
runtime: python27
api_version: 1
threadsafe: yes

instance_class: F4

inbound_services:
- channel_presence

builtins:
- deferred: on
- remote_api: on
#- appstats: on

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /zeroclipboard
  static_dir: static/lib/zeroclipboard

- url: /admin_js
  static_dir: static/admin_js

- url: /data
  static_dir: static/data

- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: /lib
  static_dir: static/lib

- url: .*/sound
  static_dir: static/sound

- url: .*
  script: handlers.artifact_app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: ssl
  version: "2.7.11"
- name: lxml
  version: "2.3"
- name: numpy
  version: "1.6.1"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^dev_data$
- ^extras$
- ^tools$